export const SET_PROJECTS = 'SET_PROJECTS';
export const FETCH_PROJECT_FAILED = 'FETCH_PROJECT_FAILED';
export const DELETE_PROJECT = 'DELETE_PROJECT';
export const UPDATE_PROJECT = 'UPDATE_PROJECT';

export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAILED = 'SIGN_IN_FAILED';
